### PR TITLE
Implement user roles 

### LINKED ISSUE #596: Implement User authorization to access properties

### PR DESCRIPTION
**Pull request by sayak-sarkar**
## Closes / Fixes / Resolves
Resolves #596 

## Explain the feature/fix
Implements User roles for `spaship-admin` and `spaship-user`.

## Does this PR introduce a breaking change
No

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

**Comment by sayak-sarkar** [comment]
@mwcz Would you be pushing any further changes to this branch or should I mark it as ready for review?

**Comment by kunyan** [comment]
There still has some security issue is when user using APIKey to upload. you will not be able to get their rover group any more

@sayak-sarkar @mwcz

**Comment by mwcz** [comment]
Interesting approach!  I hadn't considered this option when brainstorming how this might be done.  I see that you have one config property, which gets expanded into two LDAP group names.

I'd like to share how I was picturing doing this, if I had implemented it.  Then we can discuss pros and cons.  First let me describe your approach just to make sure I am understanding it.

# Implicit group configuration

In this approach, anyone deploying a SPAship instance would set the following variable:

`SPASHIP_AUTH__PROP`

The value would then be injected into a template string to generate two LDAP groups, one for regular users and one for admins.  For example:

 - SPAship admin sets `SPASHIP_AUTH__PROP=catalog`
 - SPAship injects that value into `spaship-$PROP-admins` and `spaship-$PROP-users`, resulting in the admin LDAP group of `spaship-catalog-admins` and users LDAP group of `spaship-catalog-users`

# Explicit group configuration

Here's what I was picturing.

 - `SPASHIP_AUTH__LDAP__USER_GROUPS`
 - `SPASHIP_AUTH__LDAP__ADMIN_GROUPS`

 `SPASHIP_AUTH__LDAP__USER_GROUPS` would contain the group or groups (comma-delimited) which should have read-only access, and likewise for the groups with write access.  

Example:

 - `SPASHIP_AUTH__LDAP__USER_GROUPS="gss-devs,spaship-access-users"`: all gss-devs and spaship-access-users members have read access to the SPAship instance.
 - `SPASHIP_AUTH__LDAP__ADMIN_GROUPS="spaship-maintainer,dxp-ops,cpfed`: spaship-maintainers, DXP Ops team, and CPFED team have write/deploy access to the SPAship instance.

Why I like this approach:

  1. It's more clear what the precise LDAP group names are.
  2. Pre-existing groups can be used: a team that has existing LDAP groups (ex: `gss-devs`) could choose to re-use those for SPAship access.
  3. One group name can be changed without changing the other.
  4. Multiple group names can be listed.  For instance, we could create a `spaship-maintainer` group with the four of us in it, and include that in each SPAship instance's configuration, to help us support those instances.  The teams actively using the SPAship instance could have their own admin group, separate from the maintainer group.

Let me know what you think @sayak-sarkar @kunyan @Jared-Sprague !  Let's discuss.

**Comment by kunyan** [comment]
Hi @mwcz ,

I think we have same idea. a prop with comma separate groups. It will have more flexibility to extend more groups, especially to assign the permission to the exists groups


There still has one concern is the security issue. What we talked few days before.
Here are what I'm understand

If a user in a SPAship related LDAP group, He/She is able to generate API keys.
Both admins and users are able to generate API key. so what's different between them ?
I think the user group will be store in to the APIKey collection as well

| id | apiKey              | ldap_groups      |
|----|---------------------|------------------|
| 1  | xasdasrewrtrdfhcfxx | developer, admin |
| 2  | gfhfgyerdfbhcvjngfj | developer        |


Well, that will leave some issues 
1. if user not belong to the LDAP group any more, SPAship not aware of it.
2. If a LDAP group had been removed, SPAship not aware of it.
3. If there has some reason to change the LDAP group name, The DB admin have to update the database as well


It is easy to fix those issues in the beginning. or leave bombs to the future

**Comment by sayak-sarkar** [comment]
@mwcz @kunyan Thanks for sharing your thoughts. I agree that allowing the addition of existing groups directly to an array of whitelisted LDAP groups would be a super convenient implementation. However, while doing this implementation the thought process that I was looking at this from included the following primary concerns:-

1. **Separation of concern** - Dedicated LDAP groups not only makes it super easy (using the rover interface) to add or remove individuals to certain privileged positions within SPAship, it also allows for separation of concern. A common issue involves use-cases where in due to some reasons involving other applications a certain individual is added to an existing group for example, `gss-devs`. What if this individual is not supposed to receive admin access to SPAship as well? How do we include everyone from a certain list barring a few people?
2. **Access identification from LDAP Profiles** - Another common use-case is where we often tend to do Rover / LDAP lookups  identify whether an individual has access to certain types of applications. While this is not a strong justification for this use case, think of this as a quick fire way of identifying users who have access to any SPAship property whatsoever by simply checking the names of the LDAP groups that they belong to. Hence the naming of preset groups to the tune of `spaship-<property>-<access>`

**Comment by mwcz** [comment]
@kunyan A simple solution would be to only allow Admins to create API keys.  Regular users, with their read-only access, couldn't do anything with the API key anyway.

**Comment by sayak-sarkar** [comment]
@mwcz @kunyan As discussed in today's call I have updated the `checkAccess` middleware to support user defined LDAP groups for user roles.

**Review by mwcz — APPROVED** [review]
Looks good to me!

**Pull request merged**
