### PR TITLE
refactor: apply proper type to SPAship's JWT

### PR DESCRIPTION
**Pull request by mwcz**
Apply the appropriate type to a few JWT references that were typed as `any`.

### CODE REVIEW

**Review by sayak-sarkar — APPROVED** [review]

**Comment by sayak-sarkar** [comment]
@mwcz LGTM. However, I am wondering why the builds started failing after this PR was raised.

As per https://travis-ci.com/github/spaship/spaship/builds/184972075
```sh
Failed to deploy "deploy-error" to /deploy/error: Error: EISDIR, illegal operation on a directory

Package directory not found

SPAship yaml config not found

{"message":"ENOENT, no such file or directory '/fake/webroot'","code":"ENOENT","errno":-2,"path":"/fake/webroot"}
```

**Comment by mwcz** [comment]
@sayak-sarkar I don't think this PR is the problem. :sweat_smile: 

Screenshot from 2020-09-22 07-37-20

**Comment by mwcz** [comment]
Also interesting: the build for this PR's branch passed.  The build for this PR's branch + master, failed.

**Comment by sayak-sarkar** [comment]
Yup! I saw the travis build log as well. But I'm not sure why they build is erroring out.

**Pull request merged**
