### PR TITLE
teach CLI to support API key auth and to communicate with multiple SPAship environments

### PR DESCRIPTION
**Pull request by mwcz**
Ready for review!

I'll summarize the changes here, but reading the README diff will be the best way to learn what this PR adds.  Here's the summary:

- add support for "spashiprc" files which stores information like names for environments (dev, qa, etc), URLs, and API keys for each environment.  They can be yaml or json.
- add a `--env` option to the CLI which accepts the name of a spaship env defined in a spashiprc file, _or_ the full URL to a SPAship environment
- add a `--apikey` option for passing the API key in directly
- add a "layering" method for separating URL and API key so the URLs can be committed to git, but the API keys stay local (NEVER in git).  Read the README for a description of how this works.

These three options can be used together in different ways.  There are examples in the README.

A note about spashiprc files.  Adding _another_ file is never ideal.  We already have spaship.yaml, so why add a new file?  My reasoning hinges on what info needs to be stored in git, or not.

| info | location in this PR | store in git? |
| --- | --- | --- |
| name | spaship.yaml | always |
| path | spaship.yaml | always |
| single | spaship.yaml | always |
| env URLs | .spashiprc.yml | sometimes |
| env API keys | .spashiprc.yml | never |

Some teams will want to store the env URLs stored in git.

Now that I'm writing this, perhaps a better system would be to move `envs` into spaship.yaml, and allow API keys to be provided in a layered file in a parent directory.  I won't have time to implement that, but if you guys like the idea, feel free to keep iterating on this solution.

### CODE REVIEW

**Comment by kunyan** [comment]
CI build error by `package-lock.json` missing. Please fix it

**Comment by sayak-sarkar** [comment]
I feel that moving the `envs` into the yaml file might be a better option for the sake of simplicity. However, keeping the MVP release in mind, I think for now we can keep the rc file and reiterate over this post-MVP.

**Comment by kunyan** [comment]
1. Put .spashiprc.yaml into project directory
* Good:
Easy to CI, it won't need config extra stuff
* Bad:
The apiKey will expose in git repo. The people who has access repo permission could get the key and overwrite or remove SPA

2. Put .spashiprc.yaml into $HOME
* Good:
The api key is secure. repo clean

* Bad:
Most CI do not have easy way to setup a file into $HOME. need user setup some scripts to generate it




I think the good way is put environment map into spaship.yaml.
put apiKey to $HOME/.spashiprc

Then
CI tool will be like
```
spaship deploy xxx --env qa --apiKey=xxxxxxxx
```

**Comment by kunyan** [comment]
I'm thinking about if we should provide a `proxy` component could have environment map.
User won't facing many api hosts

**Comment by kunyan** [comment]
Sorry I missed README part. LGFM

**Pull request merged**
