### PR TITLE
build: offer a way to pass API urls by env var

### PR DESCRIPTION
**Pull request by mwcz**
This is related to #77 and #165

It adds a way to pass in a list of SPAship environments via an environment variable, making it easy to configure SPA Manager simply by setting environment variables in OpenShift.

You would start by setting an environment variable that lists all the SPAship APIs you want this instance of SPA Manager to communicate with.

```
REACT_APP_SPASHIP_URLS="dev@https://spaship.dev.redhat.com qa@https://spaship.qa.redhat.com stage@https://spaship.stage.redhat.com prod@https://spaship.redhat.com"
```

The form is `name@url`, with multiple entries separated by whitespace.

Create React App offers [this technique](https://create-react-app.dev/docs/adding-custom-environment-variables/#referencing-environment-variables-in-the-html) for embedding environment variables in the app's HTML at build-time.  That's why the env above starts with "REACT_APP_".  So, if we build SPA Manager in OpenShift, we'll have access to set any environment variables we want to pass in to SPA Manager.

Here's how it looks when it's passed into index.html.

```html
<script>
  window.env = {
    SPASHIP_APIS: "%REACT_APP_SPASHIP_URLS%"
  };
</script>
```

The new module EnvParser.ts reads `window.env`, parses the SPASHIP_APIS string, and turns it into the following data structure:

```js
[
  { name: "dev", url: "https://spaship.dev.redhat.com" },
  { name: "qa", url: "https://spaship.qa.redhat.com" },
  { name: "stage", url: "https://spaship.stage.redhat.com" },
  { name: "prod", url: "https://spaship.redhat.com" }
]
```

We can use that object to populate the UI with environment names and make API calls to the URLs.

Perhaps there is a more straightforward way to configure multiple APIs.  A config file seems good, I just don't know where we'd store that file and how we'd get it into OpenShift.  I know that environment variables are trivial to set in OpenShift, so I opted for that option.

### CODE REVIEW

**Comment by mwcz** [comment]
Would anyone like to review this?  @Jared-Sprague @kunyan @sayak-sarkar

**Comment by kunyan** [comment]
https://create-react-app.dev/docs/adding-custom-environment-variables/#referencing-environment-variables-in-the-html
> The environment variables are injected at build time. If you need to inject them at runtime, follow this approach instead.

Our SPA Manager will build and running in a httpd container.
So the API hosts will be injected in build phase. it will be setup in container image. and can not be modified.

We can setup a configMap to OpenShift Build to make it work.
I'm OK with this PR if we are in same page.

**Comment by mwcz** [comment]
@kunyan Just to confirm, you are saying that it will be possible to build the Manager in OpenShift and pass in environment variables during that build?

**Comment by kunyan** [comment]
@mwcz yes, We could setup env vars into BuildConfig

https://docs.openshift.com/container-platform/3.11/dev_guide/builds/build_environment.html

**Pull request merged**
